### PR TITLE
Update runtime to 43

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
I stopped the build since there's an error.

**Comment by TheEvilSkeleton** [comment]
Error:
```
========================================================================
Building module glib in /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/glib-1
========================================================================
]2;flatpak-builder: Building glibFB: Running: tar xf /srv/buildbot/worker/downloads/downloads/200d7df811c5ba634afbf109f14bb40ba7fde670e89389885da14e27c0840742/glib-2.70.0.tar.xz --no-same-owner --strip-components=1 -J
Applying patch 0001-do-not-test-exec.patch
FB: Running: patch -p1 -i /srv/buildbot/worker/build-x86_64-2/build/0001-do-not-test-exec.patch
patching file gio/gdesktopappinfo.c
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/glib --nofilesystem=host:reset --filesystem=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/glib-1 --bind-mount=/run/build/glib=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/glib-1 --build-dir=/run/build/glib/_flatpak_build --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1664048596 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=64 /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-Ktnu9r meson --prefix=/app .. -Dtests=false -Dselinux=disabled -Dinternal_pcre=false' on host
The Meson build system
Version: 0.63.1
Source dir: /run/build/glib
Build dir: /run/build/glib/_flatpak_build
Build type: native build
../meson.build:1:0: ERROR: Unknown options: "internal_pcre"
A full log can be found at /run/build/glib/_flatpak_build/meson-logs/meson-log.txt
FB: host_command_exited_cb 3541 256
]2;flatpak-builder: Cleanup glibError: module glib: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-Ktnu9r
```

**Comment by TheEvilSkeleton** [comment]
Can you remove this line? https://github.com/flathub/org.bluesabre.MenuLibre/blob/bb4a0f9805f8da69b849ec83e856e1c2a040669a/org.bluesabre.MenuLibre.yaml#L41

**Comment by TheEvilSkeleton** [comment]
Looks like it doesn't run:
```
❯ flatpak run org.bluesabre.MenuLibre
Traceback (most recent call last):
  File "/app/bin/menulibre", line 44, in <module>
    import menulibre
  File "/app/lib/python3.10/site-packages/menulibre/__init__.py", line 23, in <module>
    from menulibre import MenulibreApplication
  File "/app/lib/python3.10/site-packages/menulibre/MenulibreApplication.py", line 34, in <module>
    from . import MenulibreTreeview, MenulibreHistory, Dialogs
  File "/app/lib/python3.10/site-packages/menulibre/MenulibreTreeview.py", line 26, in <module>
    from . import MenuEditor, MenulibreXdg, XmlMenuElementTree, util
  File "/app/lib/python3.10/site-packages/menulibre/MenuEditor.py", line 33, in <module>
    gi.require_version('GMenu', '3.0')  # noqa
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GMenu not available
```

**Comment by TheEvilSkeleton** [comment]
@bluesabre any idea?

**Comment by bluesabre** [comment]
@TheEvilSkeleton No clue. It seems like the GMenu (gnome-menus) library isn't being picked up by GObject Introspection.

**Pull request closed without merging**
